[minor][cdc][docs] Optimize styles of the Flink CDC website docs home…
apache/flink-cdc pull request #3208
Opened 2024-04-07 04:33 UTC by Laffery

Optimize styles of the Flink CDC website documentation homepage:

- support responsive styles to improve reading experience under mobile device.
- optimize the background image to avoid large blank areas and increase the information content of the first screen
- highlight the`Quick Start` button to help users find it well

Take iPhone 14pm (430px, 932px) for an example 

**Before:**
<img width="322" alt="image" src="https://github.com/apache/flink-cdc/assets/49607541/65005938-f4f3-4d9b-8740-24ab63fc7013">
<img width="322" alt="image" src="https://github.com/apache/flink-cdc/assets/49607541/3a2ec46f-4226-4e73-a92e-b7945bc8f37f">
<img width="322" alt="image" src="https://github.com/apache/flink-cdc/assets/49607541/b964b230-7460-4e92-a27c-78a07b9fcd4b">

**After:**
<img width="324" alt="image" src="https://github.com/apache/flink-cdc/assets/49607541/a558175a-23fb-4677-b31a-fc090da60f33">
<img width="320" alt="image" src="https://github.com/apache/flink-cdc/assets/49607541/b36f0491-7250-4f4c-9869-02140d95794e">
<img width="322" alt="image" src="https://github.com/apache/flink-cdc/assets/49607541/c1f64d82-9cd0-44f8-983b-be3fae4b19a6">

2024-04-07 05:53 UTC, leonardBang commented
@GOODBOY008 Would you like to help review this PR？

2024-04-07 11:38 UTC, GOODBOY008 requested changes
@Laffery Please add `/` before `fig`.

2024-04-09 04:51 UTC, Laffery commented
> @Laffery Please add `/` before `fig`. And ci will pass.

Thanks for your kind tips, I've finished and hope you review and trigger the CI again 🙏

2024-04-09 07:05 UTC, GOODBOY008 requested changes
@Laffery I left some suggestions.

2024-04-09 07:05 UTC, GOODBOY008 commented on docs/content.zh/_index.md
> +                    {{<img src="/fig/index-yaml-example.png" alt="Flink CDC Example">}}
```suggestion
                    {{< img src="/fig/index-yaml-example.png" alt="Flink CDC Example" >}}
```

2024-04-09 07:05 UTC, GOODBOY008 commented on docs/content.zh/_index.md
> +            {{<img src="/fig/cdc-flow.png" alt="Flink CDC Flow">}}
```suggestion
            {{< img src="/fig/cdc-flow.png" alt="Flink CDC Flow" >}}
```

2024-04-12 23:30 UTC, Laffery commented
> @Laffery I left some suggestions.

Ohh it's really helpful on these details, I've commited again according to your suggestions.

2024-04-15 03:06 UTC, leonardBang approved these changes
Thanks @Laffery for the contribution and @GOODBOY008 for the review, LGTM

2024-04-15 03:07 UTC, merged