[FLINK-35490] Migrate tests to JUnit 5 and AssertJ
apache/flink-cdc pull request #3742
Opened 2024-11-19 12:39 UTC by yuxiqian

This is a sequel PR based on @morazow's great work in #3395.

Currently, there are way too many unit tests and assertion frameworks, including JUnit-4 style `Assert`, JUnit-5 style Assertions, Hamcrest Matchers, AssertJ fluent assertions. JUnit 4, 5 (Jupier and Vintage) test frameworks are also used altogether, which is prone to mistakes.

Among all these solutions, AssertJ is generally regarded as the most readable and expressive, and used as the assertion standard in many other projects like Apache Iceberg.

This PR migrates all existing test cases to JUnit 5 + AssertJ combination, with an enforced rule defined in spotless style check to forbid using any other testing / asserting frameworks.

2024-11-20 08:09 UTC, yuxiqian commented
Most changes are just repetitive while some needs more attention:

* Created wrapper classes `AbstractTestBaseProxy` because Flink's original version was targeted to JUnit 4
* Created `ExternalResourceProxy` and `StaticExternalResourceProxy` to use JUnit 4 style `@Rule`s and `@ClassRule`s as JUnit 5 Extensions
* Modified `checkstyle.xml` to forbid using any other testing / asserting frameworks (copied from https://github.com/apache/iceberg/blob/main/.baseline/checkstyle/checkstyle.xml)

cc @GOODBOY008 @whhe @ruanhang1993

2024-12-01 23:49 UTC, morazow requested changes
Thanks @yuxiqian 🚀 This is massive effort, thanks a lot! 

I have added some suggestions, I will go over it again later on. Let's try to get this finalized soon

2024-12-01 23:49 UTC, morazow commented on flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/src/test/java/org/apache/flink/cdc/connectors/mongodb/source/MongoDBFullChangelogITCase.java
> +        assumeThat(parallelismSnapshot).isTrue();
Maybe remove parameterization from these tests?

2024-12-01 23:49 UTC, morazow commented on flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mysql-cdc/src/test/java/org/apache/flink/cdc/connectors/mysql/source/MySqlSourceTestBase.java
> +        Assertions.assertThat(actual).isEqualTo(expected);
Should this be `.containsExactly(expected.entrySet())`?

2024-12-01 23:49 UTC, morazow commented on tools/maven/checkstyle.xml
> +        </module>
nit: formatting

2024-12-01 23:49 UTC, morazow commented on flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/parser/JaninoCompilerTest.java
> +        Assertions.assertThat(evaluate).isEqualTo(false);
isFalse()

2024-12-01 23:49 UTC, morazow commented on flink-cdc-runtime/src/test/java/org/apache/flink/cdc/runtime/parser/JaninoCompilerTest.java
> +        Assertions.assertThat(evaluate).isEqualTo(true);
isTrue()

and below on two tests also same

2024-12-01 23:49 UTC, morazow commented on flink-cdc-migration-tests/flink-cdc-migration-testcases/src/test/java/org/apache/flink/cdc/migration/tests/MigrationTestBase.java
> +                .isEqualTo(true);
Let's use `.isTrue()`?

2024-12-01 23:49 UTC, morazow commented on flink-cdc-e2e-tests/flink-cdc-source-e2e-tests/src/test/java/org/apache/flink/cdc/connectors/tests/utils/FlinkContainerTestEnvironment.java
> +                    "No Flink version specified to run this test. Please use -DspecifiedFlinkVersion to pass one.");
Previous test has default value. But it is good idea to throw here, since the release cycle is very frequent nowadays 👍

2024-12-01 23:49 UTC, morazow commented on flink-cdc-connect/flink-cdc-source-connectors/flink-connector-mongodb-cdc/pom.xml
> +        </dependency>
Is this dependency needed?

2024-12-03 02:14 UTC, yuxiqian commented
Addressed comments and resolved conflicts.

2025-01-20 07:04 UTC, yuxiqian commented
Rebased and resolved conflicts again. Maybe we can work on this right after cutting branch to minimize the rebase chore.

2025-02-18 09:53 UTC, lvyanquan commented
I think it's a good time to complete this(Before the release of a large number of other PRs), could @yuxiqian help to resolve the confilct?

2025-02-18 10:06 UTC, yuxiqian commented
Thanks for Kunni's proposal, rebased with master and migrated a few newly added test cases.

2025-03-03 04:20 UTC, lvyanquan commented on flink-cdc-common/pom.xml
> +            </plugin>
is it necessary or added by accident?

2025-03-03 05:33 UTC, yuxiqian commented on flink-cdc-common/pom.xml
> +            </plugin>
Should be an unintentional change, reverted.

2025-03-03 06:05 UTC, lvyanquan approved these changes
LGTM.

2025-03-07 06:15 UTC, lvyanquan commented
Hi @leonardBang @ruanhang1993, could you help to check about this?

2025-03-21 09:04 UTC, yuxiqian commented
Could @leonardBang please take a look at this? Better put an end to this before moving forward to CDC 3.4.

2025-03-25 11:26 UTC, leonardBang approved these changes
Thanks @yuxiqian for the great work, LGTM

2025-03-26 08:42 UTC, merged