[FLINK-36964] Fix potential exception when SchemaChange in parallel w…
apache/flink-cdc pull request #3818
Opened 2024-12-26 10:45 UTC by lvyanquan

Fix potential exception when SchemaChange in parallel with Paimon Sink.

2024-12-27 01:33 UTC, yuxiqian commented
Hi @lvyanquan, I have some concern about how BucketAssignOperator works with schema evolution strategy.

1) FlushEvent now works as a "pipeline drain indicator", which means after all data sink writer acknowledges them, there should't be any unhandled / uncommitted events flowing the whole pipeline, so SchemaRegistry could evolve downstream DB safely.

![Normal Flush Event Semantic](https://github.com/user-attachments/assets/5403835d-ec5f-48fd-9767-b9991bc2fb31)

However, the bucket assigning strategy might break that assumption, where data sink writers might receive data change events with stale schema, even after external schema evolution processes have finished.

![Questionable FlushEvent Semantic](https://github.com/user-attachments/assets/10ec528b-e00e-44a7-8d7c-0b700c03ff7c)

2) Potential schema operator hanging risks with "distributed" topology. 

![Hanging risks](https://github.com/user-attachments/assets/0f5486d4-ec0b-4c0f-b41a-59da57abe88d)

Basically same as described in #3680. In short, if a broadcast / custom partitioning topology is applied, then blocking one upstream partition will implicitly block all downstream partitions from handling events.

3) Why we need another Bucket assigner operator?

AFAIK all data change events have been hashed & distributed in PartitionOperator. Since adding a BucketAssignOperator does not change the parallelism, is there any reason we can't calculate the correct bucket partition ID in advance, instead of creating another partitioning topology?

2024-12-27 01:38 UTC, yuxiqian commented
A little off topic, but we're really lacking E2e tests to real-life data sinks with complicated writing topologies. #3491 with higher pressure might be necessary to expose more issues like this in the future.

2025-01-07 01:51 UTC, lvyanquan commented
Hi @yuxiqian, could you help to review this?

2025-01-07 06:34 UTC, yuxiqian requested changes
Thanks for @lvyanquan's great work, just left some comments.

2025-01-07 06:34 UTC, yuxiqian commented on flink-cdc-common/src/main/java/org/apache/flink/cdc/common/utils/SchemaUtils.java
> +            }
Seems we don't need this check after `SchemaUtils#isSchemaChangeEventRedundant` has guarded us from duplicately applying non-idempotent schema change events.

2025-01-07 06:34 UTC, yuxiqian commented on flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PaimonEventSink.java
> +                        "RemoveDuplicateEvents",
Make operatorName consistent with class name

2025-01-07 06:34 UTC, yuxiqian commented on flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PreCommitOperator.java
> +            // flinkMetricGroup could be passed after FLIP-371.
Our baseline is Flink 1.19 where FLIP-371 has been resolved. Can we remove this TODO now?

2025-01-07 06:34 UTC, yuxiqian commented on flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/PreCommitOperator.java
> +                                            + checkpointId));
```suggestion
LOGGER.debug("Try to commit: {} in checkpoint {}", ...);
```

Thus, we don't need to pay for string concatenation with higher log level.

2025-01-07 06:34 UTC, yuxiqian commented on flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/bucket/BucketAssignOperator.java
> +            }
Seems we can merge `event instanceof CreateTableEvent` and `event instanceof SchemaChangeEvent`?

2025-01-07 06:34 UTC, yuxiqian commented on flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/bucket/BucketAssignOperator.java
> +        LOGGER.debug("Succeed to get table info " + table);
```suggestion
        LOGGER.debug("Succeed to get table info {}", table);
```

2025-01-07 06:34 UTC, yuxiqian commented on flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/bucket/FlushEventAlignmentOperator.java
> +/** Remove duplicate {@link FlushEvent} created by {@link BucketAssignOperator}. */
```suggestion
/** Align {@link FlushEvent}s broadcasted by {@link BucketAssignOperator}. */
```

2025-01-07 06:34 UTC, yuxiqian commented on flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/bucket/FlushEventAlignmentOperator.java
> +                                + subtaskId);
Ditto, avoid eager string concatenation

2025-01-07 06:34 UTC, yuxiqian commented on flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/bucket/FlushEventAlignmentOperator.java
> +    private transient Map<Integer, Set<Integer>> sourceTaskIdToAssignBucketSubTaskIds;
I'm not sure if it's enough to distinguish `FlushEvent`s?

Notice that each upstream partition might emit `FlushEvent`s individually, and all of them might be broadcast again in the `BucketAssignOperator`.

2025-01-07 07:12 UTC, lvyanquan commented on flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/bucket/FlushEventAlignmentOperator.java
> +    private transient Map<Integer, Set<Integer>> sourceTaskIdToAssignBucketSubTaskIds;
Each `FlushEventAlignmentOperator` will receive `FlushEvent`s with the same `sourceTaskId` of upstream partition  from `BucketAssignOperator`, each upstream partition was distinguished by `sourceTaskId`.

2025-01-07 08:28 UTC, yuxiqian commented on flink-cdc-connect/flink-cdc-pipeline-connectors/flink-cdc-pipeline-connector-paimon/src/main/java/org/apache/flink/cdc/connectors/paimon/sink/v2/bucket/FlushEventAlignmentOperator.java
> +    private transient Map<Integer, Set<Integer>> sourceTaskIdToAssignBucketSubTaskIds;
That makes sense to me.

2025-01-07 08:29 UTC, yuxiqian approved these changes
It's nice to have corresponding E2e cases to verify changes in this PR. Could @leonardBang @ruanhang1993 please trigger the CI workflow?

2025-01-08 02:51 UTC, lvyanquan commented
Last CI passed and rebase master to fix the conflict.

2025-01-09 06:56 UTC, leonardBang commented
@lvyanquan Would you like to rebase to latest master branch as conflicts happens?

2025-01-10 11:09 UTC, lvyanquan commented
Rebased to master.

2025-01-13 08:42 UTC, leonardBang approved these changes
Thanks @lvyanquan for the contribution and @yuxiqian for the review, LGTM

2025-01-13 08:43 UTC, merged