[FLINK-36981][cdc] Fix the bug of transform merging with route in YAML task
apache/flink-cdc pull request #3826
Opened 2024-12-30 17:35 UTC by aiwenmo

2024-12-31 01:23 UTC, aiwenmo commented
PTAL @yuxiqian @lvyanquan

2025-01-02 10:03 UTC, yuxiqian commented
`1.Change Map<Tuple2<TableId, TransformProjection>, TransformProjectionProcessor> transformProjectionProcessorMap into Map<Tuple2<TableId, String>, TransformProjectionProcessor> transformProjectionProcessorMap.`

Seems you're changing the key of this map from "[TableId, TransformProjection]` to `[Transform, TransformProjection#projection]`. However the problem is Projection string is a field of TransformProjection. If `TransformProjection` has collision, how can the `ProjectionString` be OK?

2025-01-02 10:24 UTC, yuxiqian requested changes

2025-01-02 10:24 UTC, yuxiqian commented on flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/PostTransformOperator.java
> +                            .hasTableInfo()) {
`hasTableInfo` could be renamed to something like `hasChangeInfo` or `hasPostTransformChangeInfo`

2025-01-02 10:24 UTC, yuxiqian commented on flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/PostTransformOperator.java
> +                                TransformProjectionProcessor.of(
We may have a `copy` method in `TransformProjectionProcessor` to allow us overwriting specific field but keep others intact.

Otherwise, a lot of codes must be modified if we add one more field into it.

2025-01-07 03:38 UTC, ChaomingZhangCN commented on flink-cdc-runtime/src/main/java/org/apache/flink/cdc/runtime/operators/transform/PostTransformOperator.java
> +                                TransformProjectionProcessor.of(
+1 Use TransformProjectionProcessor#copy() to create a non-shared object seems better.

2025-01-08 09:30 UTC, yuxiqian approved these changes
As discussed with @aiwenmo, we'll keep this PR minimal, focusing on bug-fix and leave transform module cleaning-up work later.

Could @leonardBang please trigger the CI?

2025-01-09 04:09 UTC, leonardBang approved these changes
Thanks @aiwenmo for the contribution and @yuxiqian for the review, LGTM

2025-01-09 04:13 UTC, merged